-- 051_email_templates_overdue_seeds — deadline-warning email template variants.
--
-- Phase 7.2 of the 2026-06-04 stakeholder remediation. Migration 048
-- seeded 8 stage-TRANSITION templates ('Ready for prep — ...'). This
-- migration adds 7 deadline-OVERDUE variants — one per non-terminal
-- SOP stage. The 'complete' stage is terminal (SLA = 0h) and never
-- emits a deadline-warning, so no overdue variant is seeded for it.
--
-- These templates are read by app/tasks/sop_tasks.py::
-- _maybe_send_deadline_email via app.api.email_templates.
-- resolve_template_sync, using stage_id = '<sop_stage>_overdue'. The
-- existing _VALID_STAGES validator on the async route does NOT include
-- these IDs, but the sync resolver intentionally trusts its caller and
-- queries by raw stage_id, so the resolver finds them.
--
-- Variable convention matches migration 048: {{ var_name }} (Jinja /
-- Mustache style). Substitution is regex-based via
-- app.api.email_templates.substitute_variables (no Jinja2 dependency).
-- Supported variables for overdue templates:
--   {{ session_code }}        — sessions.code
--   {{ session_title }}       — sessions.title
--   {{ assignee_first_name }} — derived from assignee email local-part
--   {{ stage }}               — overdue stage ('prep', 'medical', etc.)
--   {{ overdue_hours }}       — hours past SLA (float, one decimal)
--   {{ editor_url }}          — direct link to /e/{session_id}/sop
--   {{ results_url }}         — alias for editor_url (transition templates use this)
--
-- Soft-deletable + edit-able via Settings → Email templates. Operators
-- can override per Session Type via the EmailBuilder UI; this seed
-- creates the default-for-all-types fallback (session_type_id = NULL).

INSERT INTO email_templates (session_type_id, stage_id, locale, subject, body)
VALUES
    (NULL, 'prep_overdue', 'en-US',
     '[VIN] OVERDUE: prep — {{ session_code }} ({{ overdue_hours }}h past SLA)',
     E'<!DOCTYPE html>\n<html><body style="margin:0;padding:0;background:#F7F7F7;font-family:''ProximaNova'',Helvetica,Arial,sans-serif;color:#002855;">\n  <table cellpadding="0" cellspacing="0" border="0" width="100%" style="max-width:640px;margin:0 auto;background:#FFFFFF;">\n    <tr><td style="background:#B45A1A;padding:20px 28px;color:#FFFFFF;">\n      <div style="font-size:11px;letter-spacing:.18em;text-transform:uppercase;color:#FFD8C2;">VIN Transcript Software · SOP Alert</div>\n      <div style="font-size:18px;font-weight:800;margin-top:4px;">Prep stage overdue · {{ session_code }}</div>\n    </td></tr>\n    <tr><td style="padding:24px 28px;font-size:14px;line-height:1.6;color:#002855;">\n      <p>Hi {{ assignee_first_name }},</p>\n      <p>Session <strong>{{ session_title }}</strong> ({{ session_code }}) has been at the <strong>prep</strong> stage for <strong>{{ overdue_hours }}h past SLA</strong>.</p>\n      <p>Please open the session, verify the extras, confirm everything needed is present, and advance to copy draft. If you cannot complete prep today, reassign to unblock the pipeline.</p>\n      <p><a href="{{ editor_url }}" style="display:inline-block;background:#002855;color:#FFFFFF;padding:11px 22px;border-radius:8px;font-weight:600;text-decoration:none;">Open session →</a></p>\n    </td></tr>\n  </table>\n</body></html>'),
    (NULL, 'copy_draft_overdue', 'en-US',
     '[VIN] OVERDUE: copy_draft — {{ session_code }} ({{ overdue_hours }}h past SLA)',
     E'<!DOCTYPE html>\n<html><body style="margin:0;padding:0;background:#F7F7F7;font-family:''ProximaNova'',Helvetica,Arial,sans-serif;color:#002855;">\n  <table cellpadding="0" cellspacing="0" border="0" width="100%" style="max-width:640px;margin:0 auto;background:#FFFFFF;">\n    <tr><td style="background:#B45A1A;padding:20px 28px;color:#FFFFFF;">\n      <div style="font-size:11px;letter-spacing:.18em;text-transform:uppercase;color:#FFD8C2;">VIN Transcript Software · SOP Alert</div>\n      <div style="font-size:18px;font-weight:800;margin-top:4px;">Copy draft overdue · {{ session_code }}</div>\n    </td></tr>\n    <tr><td style="padding:24px 28px;font-size:14px;line-height:1.6;color:#002855;">\n      <p>Hi {{ assignee_first_name }},</p>\n      <p>Draft copy edit on <strong>{{ session_title }}</strong> ({{ session_code }}) is <strong>{{ overdue_hours }}h past SLA</strong>. Open the AI editor to continue, or reassign if you cannot complete today.</p>\n      <p><a href="{{ editor_url }}" style="display:inline-block;background:#002855;color:#FFFFFF;padding:11px 22px;border-radius:8px;font-weight:600;text-decoration:none;">Open editor →</a></p>\n    </td></tr>\n  </table>\n</body></html>'),
    (NULL, 'medical_overdue', 'en-US',
     '[VIN] OVERDUE: medical — {{ session_code }} ({{ overdue_hours }}h past SLA)',
     E'<!DOCTYPE html>\n<html><body style="margin:0;padding:0;background:#F7F7F7;font-family:''ProximaNova'',Helvetica,Arial,sans-serif;color:#002855;">\n  <table cellpadding="0" cellspacing="0" border="0" width="100%" style="max-width:640px;margin:0 auto;background:#FFFFFF;">\n    <tr><td style="background:#B45A1A;padding:20px 28px;color:#FFFFFF;">\n      <div style="font-size:11px;letter-spacing:.18em;text-transform:uppercase;color:#FFD8C2;">VIN Transcript Software · SOP Alert</div>\n      <div style="font-size:18px;font-weight:800;margin-top:4px;">Medical review overdue · {{ session_code }}</div>\n    </td></tr>\n    <tr><td style="padding:24px 28px;font-size:14px;line-height:1.6;color:#002855;">\n      <p>Hi {{ assignee_first_name }},</p>\n      <p>Medical review for <strong>{{ session_title }}</strong> ({{ session_code }}) is <strong>{{ overdue_hours }}h past SLA</strong>. Please review with tracked changes enabled and return to the next stage, or reassign.</p>\n      <p><a href="{{ editor_url }}" style="display:inline-block;background:#002855;color:#FFFFFF;padding:11px 22px;border-radius:8px;font-weight:600;text-decoration:none;">Open session →</a></p>\n    </td></tr>\n  </table>\n</body></html>'),
    (NULL, 'copy_final_overdue', 'en-US',
     '[VIN] OVERDUE: copy_final — {{ session_code }} ({{ overdue_hours }}h past SLA)',
     E'<!DOCTYPE html>\n<html><body style="margin:0;padding:0;background:#F7F7F7;font-family:''ProximaNova'',Helvetica,Arial,sans-serif;color:#002855;">\n  <table cellpadding="0" cellspacing="0" border="0" width="100%" style="max-width:640px;margin:0 auto;background:#FFFFFF;">\n    <tr><td style="background:#B45A1A;padding:20px 28px;color:#FFFFFF;">\n      <div style="font-size:11px;letter-spacing:.18em;text-transform:uppercase;color:#FFD8C2;">VIN Transcript Software · SOP Alert</div>\n      <div style="font-size:18px;font-weight:800;margin-top:4px;">Final copy overdue · {{ session_code }}</div>\n    </td></tr>\n    <tr><td style="padding:24px 28px;font-size:14px;line-height:1.6;color:#002855;">\n      <p>Hi {{ assignee_first_name }},</p>\n      <p>Final copy edit pass on <strong>{{ session_title }}</strong> ({{ session_code }}) is <strong>{{ overdue_hours }}h past SLA</strong>. Incorporate the medical reviewer notes, finalize speaker labels, complete the readthrough, or reassign.</p>\n      <p><a href="{{ editor_url }}" style="display:inline-block;background:#002855;color:#FFFFFF;padding:11px 22px;border-radius:8px;font-weight:600;text-decoration:none;">Open editor →</a></p>\n    </td></tr>\n  </table>\n</body></html>'),
    (NULL, 'cms_overdue', 'en-US',
     '[VIN] OVERDUE: cms — {{ session_code }} ({{ overdue_hours }}h past SLA)',
     E'<!DOCTYPE html>\n<html><body style="margin:0;padding:0;background:#F7F7F7;font-family:''ProximaNova'',Helvetica,Arial,sans-serif;color:#002855;">\n  <table cellpadding="0" cellspacing="0" border="0" width="100%" style="max-width:640px;margin:0 auto;background:#FFFFFF;">\n    <tr><td style="background:#B45A1A;padding:20px 28px;color:#FFFFFF;">\n      <div style="font-size:11px;letter-spacing:.18em;text-transform:uppercase;color:#FFD8C2;">VIN Transcript Software · SOP Alert</div>\n      <div style="font-size:18px;font-weight:800;margin-top:4px;">CMS publish overdue · {{ session_code }}</div>\n    </td></tr>\n    <tr><td style="padding:24px 28px;font-size:14px;line-height:1.6;color:#002855;">\n      <p>Hi {{ assignee_first_name }},</p>\n      <p>CMS publish for <strong>{{ session_title }}</strong> ({{ session_code }}) is <strong>{{ overdue_hours }}h past SLA</strong>. Generate the CMS-ready document, upload to VIN library, and attest CE hours.</p>\n      <p><a href="{{ editor_url }}" style="display:inline-block;background:#002855;color:#FFFFFF;padding:11px 22px;border-radius:8px;font-weight:600;text-decoration:none;">Open session →</a></p>\n    </td></tr>\n  </table>\n</body></html>'),
    (NULL, 'captions_overdue', 'en-US',
     '[VIN] OVERDUE: captions — {{ session_code }} ({{ overdue_hours }}h past SLA)',
     E'<!DOCTYPE html>\n<html><body style="margin:0;padding:0;background:#F7F7F7;font-family:''ProximaNova'',Helvetica,Arial,sans-serif;color:#002855;">\n  <table cellpadding="0" cellspacing="0" border="0" width="100%" style="max-width:640px;margin:0 auto;background:#FFFFFF;">\n    <tr><td style="background:#B45A1A;padding:20px 28px;color:#FFFFFF;">\n      <div style="font-size:11px;letter-spacing:.18em;text-transform:uppercase;color:#FFD8C2;">VIN Transcript Software · SOP Alert</div>\n      <div style="font-size:18px;font-weight:800;margin-top:4px;">Captions overdue · {{ session_code }}</div>\n    </td></tr>\n    <tr><td style="padding:24px 28px;font-size:14px;line-height:1.6;color:#002855;">\n      <p>Hi {{ assignee_first_name }},</p>\n      <p>Caption upload for <strong>{{ session_title }}</strong> ({{ session_code }}) is <strong>{{ overdue_hours }}h past SLA</strong>. The SRT is ready — upload to Wistia and complete burn-in.</p>\n      <p><a href="{{ editor_url }}" style="display:inline-block;background:#002855;color:#FFFFFF;padding:11px 22px;border-radius:8px;font-weight:600;text-decoration:none;">Open session →</a></p>\n    </td></tr>\n  </table>\n</body></html>'),
    (NULL, 'qa_overdue', 'en-US',
     '[VIN] OVERDUE: qa — {{ session_code }} ({{ overdue_hours }}h past SLA)',
     E'<!DOCTYPE html>\n<html><body style="margin:0;padding:0;background:#F7F7F7;font-family:''ProximaNova'',Helvetica,Arial,sans-serif;color:#002855;">\n  <table cellpadding="0" cellspacing="0" border="0" width="100%" style="max-width:640px;margin:0 auto;background:#FFFFFF;">\n    <tr><td style="background:#B45A1A;padding:20px 28px;color:#FFFFFF;">\n      <div style="font-size:11px;letter-spacing:.18em;text-transform:uppercase;color:#FFD8C2;">VIN Transcript Software · SOP Alert</div>\n      <div style="font-size:18px;font-weight:800;margin-top:4px;">QA overdue · {{ session_code }}</div>\n    </td></tr>\n    <tr><td style="padding:24px 28px;font-size:14px;line-height:1.6;color:#002855;">\n      <p>Hi {{ assignee_first_name }},</p>\n      <p>QA pass for <strong>{{ session_title }}</strong> ({{ session_code }}) is <strong>{{ overdue_hours }}h past SLA</strong>. Run end-to-end playback spot checks, verify mobile rendering, confirm search indexing, validate GCS G1-G14 checks pass.</p>\n      <p><a href="{{ editor_url }}" style="display:inline-block;background:#002855;color:#FFFFFF;padding:11px 22px;border-radius:8px;font-weight:600;text-decoration:none;">Open session →</a></p>\n    </td></tr>\n  </table>\n</body></html>')
ON CONFLICT ((COALESCE(session_type_id::text, '_default_')), stage_id, locale) DO NOTHING;
