"""
audit_insert_paths.py — Phase 1.5 deliverable.

Catalogues every INSERT path under app/tasks/* and notes which on-conflict
strategy each one uses. Writes a markdown report so Phase 7 + Phase 9b can
add unique indexes without repeating the mig 022 mistake (a unique index
that contradicted an existing ON CONFLICT inference path).

Output: docs/research/insert-path-audit-2026-06-05.md

Run:
    python scripts/audit_insert_paths.py
"""
from __future__ import annotations

import re
from datetime import date
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
TASKS_DIR = REPO_ROOT / "app" / "tasks"
OUTPUT = REPO_ROOT / "docs" / "research" / f"insert-path-audit-{date.today().isoformat()}.md"

# Matches INSERT INTO <table> ... [ON CONFLICT ...]. We greedily look forward
# until the next semicolon or close-paren-quote so multi-line statements get
# captured. ON CONFLICT is captured separately for the strategy column.
_INSERT_PATTERN = re.compile(
    r"INSERT\s+INTO\s+(?P<table>[a-zA-Z_][a-zA-Z0-9_]*)"
    r"(?P<body>[^;\"']*?)"
    r"(?:(?P<on_conflict>ON\s+CONFLICT[^;\"']*))?"
    r"(?=[\"';])",
    re.IGNORECASE | re.DOTALL,
)


def _classify_strategy(on_conflict: str | None) -> str:
    if on_conflict is None:
        return "NONE — caller must guard against duplicates"
    s = on_conflict.upper().strip()
    if "DO NOTHING" in s:
        return "DO NOTHING"
    if "DO UPDATE" in s:
        return "UPSERT (DO UPDATE)"
    return f"unknown — {s[:80]}"


def _scan_file(path: Path) -> list[tuple[int, str, str]]:
    """Returns (line_no, table, strategy) tuples."""
    text = path.read_text(encoding="utf-8")
    rows: list[tuple[int, str, str]] = []
    for m in _INSERT_PATTERN.finditer(text):
        # Approximate line number from the offset
        line_no = text[: m.start()].count("\n") + 1
        table = m.group("table")
        strategy = _classify_strategy(m.group("on_conflict"))
        rows.append((line_no, table, strategy))
    return rows


def main() -> int:
    if not TASKS_DIR.exists():
        print(f"No tasks dir at {TASKS_DIR}")
        return 1

    findings: list[tuple[Path, list[tuple[int, str, str]]]] = []
    for py in sorted(TASKS_DIR.glob("*.py")):
        if py.name == "__init__.py":
            continue
        rows = _scan_file(py)
        if rows:
            findings.append((py, rows))

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    with OUTPUT.open("w", encoding="utf-8") as fh:
        fh.write(f"# Insert-path audit — {date.today().isoformat()}\n\n")
        fh.write(
            "Generated by `scripts/audit_insert_paths.py` as a Phase 1.5\n"
            "deliverable. Every row below is an `INSERT INTO` in `app/tasks/*`.\n"
            "Strategy column tells you what would happen if a duplicate landed:\n"
            "* `DO NOTHING` — duplicate silently skipped (idempotent).\n"
            "* `UPSERT (DO UPDATE)` — duplicate updates the existing row.\n"
            "* `NONE` — caller must guard; uniqueness constraint will throw.\n\n"
            "Before adding a new UNIQUE index in Phase 7 or 9b, cross-check\n"
            "this list — a UNIQUE that the existing INSERT can't ON CONFLICT\n"
            "against is what broke migration 022 in 2026.\n\n"
        )
        for path, rows in findings:
            rel = path.relative_to(REPO_ROOT).as_posix()
            fh.write(f"## {rel}\n\n")
            fh.write("| Line | Table | Strategy |\n|---|---|---|\n")
            for line_no, table, strategy in rows:
                fh.write(f"| {line_no} | `{table}` | {strategy} |\n")
            fh.write("\n")

    print(f"Wrote {OUTPUT}")
    print(f"Scanned {len(findings)} files, "
          f"{sum(len(r) for _, r in findings)} INSERT paths")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
